version: '3.9'

services:
  mongo:
    image: mongo:5.0.3-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
    env_file:
      - .env
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      # Because this container will be used for production we do not expose port on
      # public interface (use `ssh` proxying for secure access to Mongo Admin if you need it
      # in production)
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo

  node:
    image: ghcr.io/thenewboston-developers/node:latest
    command: ./run.sh
    environment:
      TNB_DATABASES: '{"default": {"CLIENT": {"host": "mongo", "password": "${MONGO_INITDB_ROOT_PASSWORD}"}}}'
    env_file:
      - .env
    depends_on:
      - mongo

  reverse-proxy:
    image: ghcr.io/thenewboston-developers/reverse-proxy:latest
    ports:
      - 8555:8555
    depends_on:
      - node

volumes:
  mongo-db:
    driver: local
  mongo-configdb:
    driver: local
