# Generated by Django 3.2.9 on 2021-12-04 19:00

from django.db import migrations, models

import node.blockchain.validators
from node.core.fields import NullableJSONField


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='AccountState',
            fields=[
                (
                    '_id',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[node.blockchain.validators.HexStringValidator(64)],
                        verbose_name='Account number'
                    )
                ),
                ('balance', models.PositiveBigIntegerField(default=0)),
                (
                    'account_lock',
                    models.CharField(max_length=64, validators=[node.blockchain.validators.HexStringValidator(64)])
                ),
                ('node', NullableJSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                (
                    '_id',
                    models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Block number')
                ),
                ('body', models.BinaryField()),
            ],
        ),
    ]
