# Generated by Django 3.2.9 on 2021-11-13 19:29

from django.db import migrations, models
import djongo.models.fields
import node.blockchain.models.djongo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('own_value', models.CharField(max_length=100)),
                ('signed_change_request', djongo.models.fields.EmbeddedField(model_container=node.blockchain.models.djongo.ChangeRequest)),
                ('updates', djongo.models.fields.ArrayField(model_container=node.blockchain.models.djongo.Update)),
            ],
        ),
    ]
