# Generated by Django 3.2.9 on 2021-11-14 14:59

import djongo.models.fields
from django.db import migrations, models

import node.blockchain.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    '_id',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[node.blockchain.validators.HexStringValidator(64)],
                        verbose_name='Account number'
                    )
                ),
                ('balance', models.IntegerField()),
                (
                    'lock',
                    models.CharField(max_length=64, validators=[node.blockchain.validators.HexStringValidator(64)])
                ),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                (
                    '_id',
                    models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Block number')
                ),
                (
                    'signer',
                    models.CharField(max_length=64, validators=[node.blockchain.validators.HexStringValidator(64)])
                ),
                (
                    'signature',
                    models.CharField(max_length=128, validators=[node.blockchain.validators.HexStringValidator(128)])
                ),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                (
                    '_id',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[node.blockchain.validators.HexStringValidator(64)],
                        verbose_name='Identifier'
                    )
                ),
                ('fee', models.IntegerField()),
                ('network_addresses', djongo.models.fields.JSONField()),
            ],
        ),
    ]
