# Generated by Django 3.2.9 on 2021-12-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blockchain.accountstate',),
        ),
    ]
