# Generated by Django 3.2.9 on 2021-12-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Lock name')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blockchain.accountstate',),
        ),
    ]
