# Generated by Django 3.2.12 on 2022-03-13 06:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('hash', models.CharField(max_length=128)),
                ('body', models.BinaryField()),
            ],
            options={
                'ordering': ('number', 'hash'),
                'unique_together': {('number', 'hash')},
            },
        ),
    ]
