# Generated by Django 3.2.12 on 2022-03-12 18:51

import django.db.models.deletion
from django.db import migrations, models

import node.blockchain.validators
import node.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_node'),
    ]

    operations = [
        migrations.DeleteModel(name='Schedule',),
        migrations.DeleteModel(name='Node',),
        migrations.RenameField(
            model_name='accountstate',
            old_name='_id',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='accountstate',
            name='node',
        ),
        migrations.AlterField(
            model_name='accountstate',
            name='identifier',
            field=models.CharField(
                db_column='_id',
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[node.blockchain.validators.HexStringValidator(64)],
                verbose_name='Account number'
            ),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                (
                    'accountstate_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='blockchain.accountstate'
                    )
                ),
                ('addresses', node.core.fields.NullableJSONField(blank=True, null=True)),
                ('fee', models.PositiveBigIntegerField(default=0)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Block number')),
                (
                    'role',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'PRIMARY_VALIDATOR'), (2, 'CONFIRMATION_VALIDATOR'), (3, 'REGULAR_NODE')],
                        default=3
                    )
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('blockchain.accountstate',),
        ),
    ]
