# Generated by Django 3.2.12 on 2022-03-19 10:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_pendingblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockConfirmation',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('hash', models.CharField(max_length=128)),
                ('signer', models.CharField(max_length=64)),
                ('body', models.BinaryField()),
            ],
            options={
                'ordering': ('number', 'signer'),
                'unique_together': {('number', 'signer')},
            },
        ),
    ]
