name: Continuous integration

on:
  push:
    branches:
      - ${{ secrets.NODE_GITHUB_BRANCH }}

jobs:
# github does not support dependencies on other workflows therefore we have to duplicate the code
# QUALITY-ASSURANCE-START
  quality-assurance:
    name: Quality Assurance

    runs-on: ubuntu-latest
    container: python:3.9.9-buster

    services:
      # TODO(dmu) LOW: This section duplicates services already defined in `docker-compose.yml`.
      #                Is there a way to make it DRY?
      mongo:
        image: mongo:5.0.3-focal
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12

      - name: Install
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          TNB_DATABASES: '{"default":{"CLIENT":{"host":"mongo"}}}'
          TNB_SECRET_KEY: dummy
          TNB_NODE_SIGNING_KEY: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
# QUALITY-ASSURANCE-END

  publish-image:
    name: Publish docker images
    needs: quality-assurance
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.NODE_GITHUB_TOKEN }}
      - name: Push node image to Github Packages
        uses: docker/build-push-action@v2
        with:
          target: node
          tags: ghcr.io/thenewboston-developers/node:latest
          push: true
          # TODO(dmu) LOW: Make a better way of forcing the download of latest blockchain state
          no-cache: true
      - name: Push reverse-proxy image to Github Packages
        uses: docker/build-push-action@v2
        with:
          target: reverse-proxy
          tags: ghcr.io/thenewboston-developers/reverse-proxy:latest
          push: true
          no-cache: true

  deploy:
    name: Deploy to develoment environment
    needs: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        # TODO(dmu) MEDIUM: Once/if github implements secrets on job level
        #                   https://github.com/actions/runner/issues/520#issuecomment-877193387
        if: ${{ env.NODE_CONTINUOUS_DEPLOYMENT_ENABLED == 'True' }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $DEPLOY_SSH_HOST
            User $DEPLOY_SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
        env:
          NODE_CONTINUOUS_DEPLOYMENT_ENABLED: ${{ secrets.NODE_CONTINUOUS_DEPLOYMENT_ENABLED }}
          DEPLOY_SSH_KEY: ${{ secrets.NODE_DEPLOY_SSH_KEY }}
          DEPLOY_SSH_HOST: ${{ secrets.NODE_DEPLOY_SSH_HOST }}
          DEPLOY_SSH_USER: ${{ secrets.NODE_DEPLOY_SSH_USER }}

      - name: Run deploy
        run: |
          ssh target "docker system prune --all --volumes --force && wget https://raw.githubusercontent.com/thenewboston-developers/Node/$GITHUB_BRANCH/scripts/deploy.sh -O /tmp/deploy-node.sh && chmod a+x /tmp/deploy-node.sh && /tmp/deploy-node.sh $GITHUB_ACTOR $GITHUB_PASSWORD $GITHUB_BRANCH False False && rm -f /tmp/deploy-node.sh"
        env:
          GITHUB_PASSWORD: ${{ secrets.NODE_GITHUB_TOKEN }}
          GITHUB_BRANCH: ${{ secrets.NODE_GITHUB_BRANCH }}
