NODE_SIGNING_KEY = NotImplemented

NODE_NETWORK_ADDRESSES: list[str] = []
NODE_PORT = 8555
APPEND_AUTO_DETECTED_NETWORK_ADDRESS = True
NODE_FEE = 4

IN_DOCKER = False

NODE_LIST_JSON_PATH = None

SYNC_BATCH_SIZE = 10

SCHEDULE_CAPACITY = 20
